<?php

declare(strict_types=1);



namespace CodeIgniter\Database\OCI8;

use CodeIgniter\Database\Forge as BaseForge;


class Forge extends BaseForge
{
    
    protected $dropIndexStr = 'DROP INDEX %s';

    
    protected $createDatabaseStr = false;

    
    protected $createTableIfStr = false;

    
    protected $dropTableIfStr = false;

    
    protected $dropDatabaseStr = false;

    
    protected $unsigned = false;

    
    protected $null = 'NULL';

    
    protected $renameTableStr = 'ALTER TABLE %s RENAME TO %s';

    
    protected $dropConstraintStr = 'ALTER TABLE %s DROP CONSTRAINT %s';

    
    protected $fkAllowActions = ['CASCADE', 'SET NULL', 'NO ACTION'];

    
    protected function _alterTable(string $alterType, string $table, $processedFields)
    {
        $sql = 'ALTER TABLE ' . $this->db->escapeIdentifiers($table);

        if ($alterType === 'DROP') {
            $columnNamesToDrop = $processedFields;

            $fields = array_map(
                fn ($field) => $this->db->escapeIdentifiers(trim($field)),
                is_string($columnNamesToDrop) ? explode(',', $columnNamesToDrop) : $columnNamesToDrop,
            );

            return $sql . ' DROP (' . implode(',', $fields) . ') CASCADE CONSTRAINT INVALIDATE';
        }

        if ($alterType === 'CHANGE') {
            $alterType = 'MODIFY';
        }

        $nullableMap = array_column($this->db->getFieldData($table), 'nullable', 'name');
        $sqls        = [];

        for ($i = 0, $c = count($processedFields); $i < $c; $i++) {
            if ($alterType === 'MODIFY') {
                
                
                
                
                
                $wantToAddNull   = ! str_contains($processedFields[$i]['null'], ' NOT');
                $currentNullable = $nullableMap[$processedFields[$i]['name']];

                if ($wantToAddNull && $currentNullable === true) {
                    $processedFields[$i]['null'] = '';
                } elseif ($processedFields[$i]['null'] === '' && $currentNullable === false) {
                    
                    $processedFields[$i]['null'] = ' NULL';
                } elseif ($wantToAddNull === false && $currentNullable === false) {
                    $processedFields[$i]['null'] = '';
                }
            }

            if ($processedFields[$i]['_literal'] !== false) {
                $processedFields[$i] = "\n\t" . $processedFields[$i]['_literal'];
            } else {
                $processedFields[$i]['_literal'] = "\n\t" . $this->_processColumn($processedFields[$i]);

                if (! empty($processedFields[$i]['comment'])) {
                    $sqls[] = 'COMMENT ON COLUMN '
                        . $this->db->escapeIdentifiers($table) . '.' . $this->db->escapeIdentifiers($processedFields[$i]['name'])
                        . ' IS ' . $processedFields[$i]['comment'];
                }

                if ($alterType === 'MODIFY' && ! empty($processedFields[$i]['new_name'])) {
                    $sqls[] = $sql . ' RENAME COLUMN ' . $this->db->escapeIdentifiers($processedFields[$i]['name'])
                        . ' TO ' . $this->db->escapeIdentifiers($processedFields[$i]['new_name']);
                }

                $processedFields[$i] = "\n\t" . $processedFields[$i]['_literal'];
            }
        }

        $sql .= ' ' . $alterType . ' ';
        $sql .= count($processedFields) === 1
                ? $processedFields[0]
                : '(' . implode(',', $processedFields) . ')';

        
        array_unshift($sqls, $sql);

        return $sqls;
    }

    
    protected function _attributeAutoIncrement(array &$attributes, array &$field)
    {
        if (! empty($attributes['AUTO_INCREMENT']) && $attributes['AUTO_INCREMENT'] === true
            && str_contains(strtolower($field['type']), 'number')
            && version_compare($this->db->getVersion(), '12.1', '>=')
        ) {
            $field['auto_increment'] = ' GENERATED BY DEFAULT ON NULL AS IDENTITY';
        }
    }

    
    protected function _processColumn(array $processedField): string
    {
        $constraint = '';
        
        if ($processedField['type'] === 'VARCHAR2' && str_starts_with($processedField['length'], "('")) {
            $constraint = ' CHECK(' . $this->db->escapeIdentifiers($processedField['name'])
                . ' IN ' . $processedField['length'] . ')';

            $processedField['length'] = '(' . max(array_map(mb_strlen(...), explode("','", mb_substr($processedField['length'], 2, -2)))) . ')' . $constraint;
        } elseif (isset($this->primaryKeys['fields']) && count($this->primaryKeys['fields']) === 1 && $processedField['name'] === $this->primaryKeys['fields'][0]) {
            $processedField['unique'] = '';
        }

        return $this->db->escapeIdentifiers($processedField['name'])
           . ' ' . $processedField['type'] . $processedField['length']
           . $processedField['unsigned']
           . $processedField['default']
           . $processedField['auto_increment']
           . $processedField['null']
           . $processedField['unique'];
    }

    
    protected function _attributeType(array &$attributes)
    {
        
        
        switch (strtoupper($attributes['TYPE'])) {
            case 'TINYINT':
                $attributes['CONSTRAINT'] ??= 3;

                
            case 'SMALLINT':
                $attributes['CONSTRAINT'] ??= 5;

                
            case 'MEDIUMINT':
                $attributes['CONSTRAINT'] ??= 7;

                
            case 'INT':
            case 'INTEGER':
                $attributes['CONSTRAINT'] ??= 11;

                
            case 'BIGINT':
                $attributes['CONSTRAINT'] ??= 19;

                
            case 'NUMERIC':
                $attributes['TYPE'] = 'NUMBER';

                return;

            case 'BOOLEAN':
                $attributes['TYPE']       = 'NUMBER';
                $attributes['CONSTRAINT'] = 1;
                $attributes['UNSIGNED']   = true;

                return;

            case 'DOUBLE':
                $attributes['TYPE'] = 'FLOAT';
                $attributes['CONSTRAINT'] ??= 126;

                return;

            case 'DATETIME':
            case 'TIME':
                $attributes['TYPE'] = 'DATE';

                return;

            case 'SET':
            case 'ENUM':
            case 'VARCHAR':
                $attributes['CONSTRAINT'] ??= 255;

                
            case 'TEXT':
            case 'MEDIUMTEXT':
                $attributes['CONSTRAINT'] ??= 4000;
                $attributes['TYPE'] = 'VARCHAR2';
        }
    }

    
    protected function _dropTable(string $table, bool $ifExists, bool $cascade)
    {
        $sql = parent::_dropTable($table, $ifExists, $cascade);

        if ($sql !== true && $cascade) {
            $sql .= ' CASCADE CONSTRAINTS PURGE';
        } elseif ($sql !== true) {
            $sql .= ' PURGE';
        }

        return $sql;
    }

    
    protected function _dropKeyAsConstraint(string $table, string $constraintName): string
    {
        return "SELECT constraint_name FROM all_constraints WHERE table_name = '"
            . trim($table, '"') . "' AND index_name = '"
            . trim($constraintName, '"') . "'";
    }
}
